const path = require('path')
const fs = require('fs')

const writeTemplate = (templatePath, destination, templateValues = {}) => {
  const templateString = fs.readFileSync(
    path.join(__dirname, templatePath),
    'utf-8'
  )

  const template = templatized(templateString, templateValues)
  fs.writeFileSync(
    destination,
    '// This file was generated by RedwoodJS\n' + template
  )
}

const templatized = (template, vars = {}) => {
  const handler = new Function(
    'vars',
    [
      'const tagged = ( ' + Object.keys(vars).join(', ') + ' ) =>',
      '`' + template + '`',
      'return tagged(...Object.values(vars))',
    ].join('\n')
  )

  return handler(vars)
}

module.exports = { writeTemplate }
